// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pos.EfCore.Context;

#nullable disable

namespace Pos.EfCore.Migrations
{
    [DbContext(typeof(CloudContext))]
    [Migration("20240510124817_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CloudDomain.Domain.AppSetting", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<DateTime>("CTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("CUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("MTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("MUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("PreviousID")
                        .HasColumnType("int");

                    b.Property<Guid?>("SharedLineId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ID");

                    b.ToTable("AppSetting");
                });

            modelBuilder.Entity("CloudDomain.Domain.Application", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<DateTime>("CTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("CUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("ExeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsAssignable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("MTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("MUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("StartAfterInstall")
                        .HasColumnType("bit");

                    b.Property<int>("StartMode")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Application");

                    b.HasData(
                        new
                        {
                            ID = 1L,
                            CTime = new DateTime(2024, 5, 10, 12, 48, 17, 29, DateTimeKind.Utc).AddTicks(6879),
                            ExeName = "Giftcard.exe",
                            IsAssignable = true,
                            IsDeleted = false,
                            Name = "PurePOSGiftcardService",
                            StartAfterInstall = false,
                            StartMode = 3
                        },
                        new
                        {
                            ID = 2L,
                            CTime = new DateTime(2024, 5, 10, 12, 48, 17, 29, DateTimeKind.Utc).AddTicks(6992),
                            ExeName = "PosCloudConnector.exe",
                            IsAssignable = true,
                            IsDeleted = false,
                            Name = "PccService",
                            StartAfterInstall = false,
                            StartMode = 2
                        },
                        new
                        {
                            ID = 3L,
                            CTime = new DateTime(2024, 5, 10, 12, 48, 17, 29, DateTimeKind.Utc).AddTicks(7006),
                            ExeName = "DbSyncConsole.exe",
                            IsAssignable = true,
                            IsDeleted = false,
                            Name = "PosSyncService",
                            StartAfterInstall = false,
                            StartMode = 3
                        },
                        new
                        {
                            ID = 4L,
                            CTime = new DateTime(2024, 5, 10, 12, 48, 17, 29, DateTimeKind.Utc).AddTicks(7018),
                            ExeName = "PosCommissionService.exe",
                            IsAssignable = true,
                            IsDeleted = false,
                            Name = "PurePOSCommissionService",
                            StartAfterInstall = false,
                            StartMode = 3
                        },
                        new
                        {
                            ID = 5L,
                            CTime = new DateTime(2024, 5, 10, 12, 48, 17, 29, DateTimeKind.Utc).AddTicks(7031),
                            ExeName = "PosScheduleService.exe",
                            IsAssignable = true,
                            IsDeleted = false,
                            Name = "PurePOSScheduleService",
                            StartAfterInstall = false,
                            StartMode = 3
                        });
                });

            modelBuilder.Entity("CloudDomain.Domain.ConnectedApp", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<long>("ApplicationId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("CUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("ConnectionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsConnected")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("MTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("MUserId")
                        .HasColumnType("bigint");

                    b.Property<long>("StationId")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("StationId");

                    b.ToTable("ConnectedApp");
                });

            modelBuilder.Entity("CloudDomain.Domain.EmailSetting", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<DateTime>("CTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("CUserId")
                        .HasColumnType("bigint");

                    b.Property<bool>("EnableSSL")
                        .HasColumnType("bit");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("MTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("MUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Port")
                        .HasColumnType("int");

                    b.Property<string>("SenderEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TimeOut")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("EmailSetting");
                });

            modelBuilder.Entity("CloudDomain.Domain.InstallLog", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<long>("ApplicationId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("CUserId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("MTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("MUserId")
                        .HasColumnType("bigint");

                    b.Property<int>("StartMode")
                        .HasColumnType("int");

                    b.Property<long>("StationId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("StationId");

                    b.ToTable("InstallLog");
                });

            modelBuilder.Entity("CloudDomain.Domain.Menu", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<DateTime>("CTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("CUserId")
                        .HasColumnType("bigint");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("Expanded")
                        .HasColumnType("bit");

                    b.Property<string>("Href")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconUri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("MTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("MUserId")
                        .HasColumnType("bigint");

                    b.Property<long>("ParentID")
                        .HasColumnType("bigint");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Menu");
                });

            modelBuilder.Entity("CloudDomain.Domain.Module", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<DateTime>("CTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("CUserId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPack")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("MTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("MUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Module");
                });

            modelBuilder.Entity("CloudDomain.Domain.Page", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<DateTime>("CTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("CUserId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("MTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("MUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PurePosId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Page");

                    b.HasData(
                        new
                        {
                            ID = 1L,
                            CTime = new DateTime(2024, 5, 10, 12, 48, 17, 29, DateTimeKind.Utc).AddTicks(7227),
                            IsDeleted = false,
                            Name = "Settings (Category)",
                            PurePosId = 1
                        },
                        new
                        {
                            ID = 2L,
                            CTime = new DateTime(2024, 5, 10, 12, 48, 17, 29, DateTimeKind.Utc).AddTicks(7242),
                            IsDeleted = false,
                            Name = "Users",
                            PurePosId = 2
                        },
                        new
                        {
                            ID = 3L,
                            CTime = new DateTime(2024, 5, 10, 12, 48, 17, 29, DateTimeKind.Utc).AddTicks(7255),
                            IsDeleted = false,
                            Name = "User Settings",
                            PurePosId = 3
                        },
                        new
                        {
                            ID = 4L,
                            CTime = new DateTime(2024, 5, 10, 12, 48, 17, 29, DateTimeKind.Utc).AddTicks(7266),
                            IsDeleted = false,
                            Name = "Company",
                            PurePosId = 6
                        },
                        new
                        {
                            ID = 5L,
                            CTime = new DateTime(2024, 5, 10, 12, 48, 17, 29, DateTimeKind.Utc).AddTicks(7278),
                            IsDeleted = false,
                            Name = "Company Region",
                            PurePosId = 7
                        },
                        new
                        {
                            ID = 6L,
                            CTime = new DateTime(2024, 5, 10, 12, 48, 17, 29, DateTimeKind.Utc).AddTicks(7290),
                            IsDeleted = false,
                            Name = "Shop",
                            PurePosId = 8
                        },
                        new
                        {
                            ID = 7L,
                            CTime = new DateTime(2024, 5, 10, 12, 48, 17, 29, DateTimeKind.Utc).AddTicks(7301),
                            IsDeleted = false,
                            Name = "Warehouse",
                            PurePosId = 9
                        },
                        new
                        {
                            ID = 8L,
                            CTime = new DateTime(2024, 5, 10, 12, 48, 17, 29, DateTimeKind.Utc).AddTicks(7311),
                            IsDeleted = false,
                            Name = "Product Management",
                            PurePosId = 10
                        },
                        new
                        {
                            ID = 9L,
                            CTime = new DateTime(2024, 5, 10, 12, 48, 17, 29, DateTimeKind.Utc).AddTicks(7322),
                            IsDeleted = false,
                            Name = "Brand",
                            PurePosId = 11
                        },
                        new
                        {
                            ID = 10L,
                            CTime = new DateTime(2024, 5, 10, 12, 48, 17, 29, DateTimeKind.Utc).AddTicks(7334),
                            IsDeleted = false,
                            Name = "Model",
                            PurePosId = 12
                        },
                        new
                        {
                            ID = 11L,
                            CTime = new DateTime(2024, 5, 10, 12, 48, 17, 29, DateTimeKind.Utc).AddTicks(7345),
                            IsDeleted = false,
                            Name = "Season",
                            PurePosId = 13
                        },
                        new
                        {
                            ID = 12L,
                            CTime = new DateTime(2024, 5, 10, 12, 48, 17, 29, DateTimeKind.Utc).AddTicks(7356),
                            IsDeleted = false,
                            Name = "Vat",
                            PurePosId = 18
                        });
                });

            modelBuilder.Entity("CloudDomain.Domain.ReleaseDetail", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<long>("ApplicationId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("CUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("MTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("MUserId")
                        .HasColumnType("bigint");

                    b.Property<long>("PageId")
                        .HasColumnType("bigint");

                    b.Property<long>("ReleaseNumberId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("PageId");

                    b.HasIndex("ReleaseNumberId");

                    b.ToTable("ReleaseDetail");
                });

            modelBuilder.Entity("CloudDomain.Domain.ReleaseNumber", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<DateTime>("CTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("CUserId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("MTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("MUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("ReleaseNumber");
                });

            modelBuilder.Entity("CloudDomain.Domain.Report", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<DateTime>("CTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("CUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconUri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("MTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("MUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Report");
                });

            modelBuilder.Entity("CloudDomain.Domain.Role", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<DateTime>("CTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("CUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("MTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("MUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("CloudDomain.Domain.Shop", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<DateTime>("CTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("CUserId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("MTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("MUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ShopGroupId")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("ShopGroupId");

                    b.ToTable("Shop");

                    b.HasData(
                        new
                        {
                            ID = 1L,
                            CTime = new DateTime(2024, 5, 10, 12, 48, 17, 29, DateTimeKind.Utc).AddTicks(7079),
                            IsDeleted = false,
                            MTime = new DateTime(2024, 5, 10, 12, 48, 17, 29, DateTimeKind.Utc).AddTicks(7081),
                            Name = "Default Shop",
                            ShopGroupId = 1L
                        });
                });

            modelBuilder.Entity("CloudDomain.Domain.ShopGroup", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<DateTime>("CTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("CUserId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("MTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("MUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("ShopGroup");

                    b.HasData(
                        new
                        {
                            ID = 1L,
                            CTime = new DateTime(2024, 5, 10, 12, 48, 17, 29, DateTimeKind.Utc).AddTicks(7050),
                            IsDeleted = false,
                            MTime = new DateTime(2024, 5, 10, 12, 48, 17, 29, DateTimeKind.Utc).AddTicks(7053),
                            Name = "Default Group"
                        });
                });

            modelBuilder.Entity("CloudDomain.Domain.ShopSetting", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<DateTime>("CTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("CUserId")
                        .HasColumnType("bigint");

                    b.Property<int>("ConcurrentBoCount")
                        .HasColumnType("int");

                    b.Property<int>("ConcurrentFoCount")
                        .HasColumnType("int");

                    b.Property<string>("DatabaseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("DefaultReportId")
                        .HasColumnType("bigint");

                    b.Property<long>("EmailSettingId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LicenseExpireDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("MTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("MUserId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ReportID")
                        .HasColumnType("bigint");

                    b.Property<long>("ShopId")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("EmailSettingId");

                    b.HasIndex("ReportID");

                    b.ToTable("ShopSetting");
                });

            modelBuilder.Entity("CloudDomain.Domain.Station", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<DateTime>("CTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("CUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("HostName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("MTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("MUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("MacAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ShopId")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("ShopId");

                    b.ToTable("Station");
                });

            modelBuilder.Entity("CloudDomain.Domain.StationApp", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<long>("ApplicationId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("CUserId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("MTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("MUserId")
                        .HasColumnType("bigint");

                    b.Property<bool>("StartAfterInstall")
                        .HasColumnType("bit");

                    b.Property<int>("StartMode")
                        .HasColumnType("int");

                    b.Property<long>("StationId")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("StationId");

                    b.ToTable("StationApp");
                });

            modelBuilder.Entity("CloudDomain.Domain.User", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<DateTime>("CTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("CUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsValidated")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("MTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("MUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RememberMe")
                        .HasColumnType("bit");

                    b.Property<long>("ShopId")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("ShopId");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            ID = 1L,
                            CTime = new DateTime(2024, 5, 10, 12, 48, 17, 29, DateTimeKind.Utc).AddTicks(7141),
                            Email = "admin@posmanager.nl",
                            IsDeleted = false,
                            IsValidated = true,
                            MTime = new DateTime(2024, 5, 10, 12, 48, 17, 29, DateTimeKind.Utc).AddTicks(7144),
                            Password = "PoS666",
                            RememberMe = true,
                            ShopId = 1L
                        },
                        new
                        {
                            ID = 2L,
                            CTime = new DateTime(2024, 5, 10, 12, 48, 17, 29, DateTimeKind.Utc).AddTicks(7163),
                            Email = "admin",
                            IsDeleted = false,
                            IsValidated = true,
                            MTime = new DateTime(2024, 5, 10, 12, 48, 17, 29, DateTimeKind.Utc).AddTicks(7165),
                            Password = "1",
                            RememberMe = true,
                            ShopId = 1L
                        });
                });

            modelBuilder.Entity("CloudDomain.EmailLog", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<string>("AttachmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AttachmentUri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bcc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("CUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Cc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSent")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("MTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("MUserId")
                        .HasColumnType("bigint");

                    b.Property<long>("ShopId")
                        .HasColumnType("bigint");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("ShopId");

                    b.ToTable("EmailLog");
                });

            modelBuilder.Entity("MenuRole", b =>
                {
                    b.Property<long>("MenusID")
                        .HasColumnType("bigint");

                    b.Property<long>("RolesID")
                        .HasColumnType("bigint");

                    b.HasKey("MenusID", "RolesID");

                    b.HasIndex("RolesID");

                    b.ToTable("MenuRole");
                });

            modelBuilder.Entity("ModulePage", b =>
                {
                    b.Property<long>("ModulesID")
                        .HasColumnType("bigint");

                    b.Property<long>("PagesID")
                        .HasColumnType("bigint");

                    b.HasKey("ModulesID", "PagesID");

                    b.HasIndex("PagesID");

                    b.ToTable("ModulePage");
                });

            modelBuilder.Entity("ReleaseNumberShop", b =>
                {
                    b.Property<long>("ReleaseNumbersID")
                        .HasColumnType("bigint");

                    b.Property<long>("ShopsID")
                        .HasColumnType("bigint");

                    b.HasKey("ReleaseNumbersID", "ShopsID");

                    b.HasIndex("ShopsID");

                    b.ToTable("ShopReleaseNumber", (string)null);
                });

            modelBuilder.Entity("ReleaseNumberShopGroup", b =>
                {
                    b.Property<long>("ReleaseNumbersID")
                        .HasColumnType("bigint");

                    b.Property<long>("ShopGroupsID")
                        .HasColumnType("bigint");

                    b.HasKey("ReleaseNumbersID", "ShopGroupsID");

                    b.HasIndex("ShopGroupsID");

                    b.ToTable("ShopGroupReleaseNumber", (string)null);
                });

            modelBuilder.Entity("ReportShop", b =>
                {
                    b.Property<long>("ReportsID")
                        .HasColumnType("bigint");

                    b.Property<long>("ShopsID")
                        .HasColumnType("bigint");

                    b.HasKey("ReportsID", "ShopsID");

                    b.HasIndex("ShopsID");

                    b.ToTable("ReportShop");
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.Property<long>("RolesID")
                        .HasColumnType("bigint");

                    b.Property<long>("UsersID")
                        .HasColumnType("bigint");

                    b.HasKey("RolesID", "UsersID");

                    b.HasIndex("UsersID");

                    b.ToTable("RoleUser");
                });

            modelBuilder.Entity("CloudDomain.Domain.ConnectedApp", b =>
                {
                    b.HasOne("CloudDomain.Domain.Application", null)
                        .WithMany("ConnectedApps")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CloudDomain.Domain.Station", null)
                        .WithMany("ConnectedApps")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CloudDomain.Domain.InstallLog", b =>
                {
                    b.HasOne("CloudDomain.Domain.Application", null)
                        .WithMany("InstallLogs")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CloudDomain.Domain.Station", null)
                        .WithMany("InstallLogs")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CloudDomain.Domain.ReleaseDetail", b =>
                {
                    b.HasOne("CloudDomain.Domain.Application", null)
                        .WithMany("ReleaseDetails")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CloudDomain.Domain.Page", null)
                        .WithMany("ReleaseDetails")
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CloudDomain.Domain.ReleaseNumber", null)
                        .WithMany("ReleaseDetails")
                        .HasForeignKey("ReleaseNumberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CloudDomain.Domain.Shop", b =>
                {
                    b.HasOne("CloudDomain.Domain.ShopGroup", null)
                        .WithMany("Shops")
                        .HasForeignKey("ShopGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CloudDomain.Domain.ShopSetting", b =>
                {
                    b.HasOne("CloudDomain.Domain.EmailSetting", null)
                        .WithMany("ShopSettings")
                        .HasForeignKey("EmailSettingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CloudDomain.Domain.Report", null)
                        .WithMany("ShopSettings")
                        .HasForeignKey("ReportID");
                });

            modelBuilder.Entity("CloudDomain.Domain.Station", b =>
                {
                    b.HasOne("CloudDomain.Domain.Shop", null)
                        .WithMany("Stations")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CloudDomain.Domain.StationApp", b =>
                {
                    b.HasOne("CloudDomain.Domain.Application", null)
                        .WithMany("StationApps")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CloudDomain.Domain.Station", null)
                        .WithMany("StationApps")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CloudDomain.Domain.User", b =>
                {
                    b.HasOne("CloudDomain.Domain.Shop", null)
                        .WithMany("Users")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CloudDomain.EmailLog", b =>
                {
                    b.HasOne("CloudDomain.Domain.Shop", null)
                        .WithMany("EmailLogs")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MenuRole", b =>
                {
                    b.HasOne("CloudDomain.Domain.Menu", null)
                        .WithMany()
                        .HasForeignKey("MenusID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CloudDomain.Domain.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ModulePage", b =>
                {
                    b.HasOne("CloudDomain.Domain.Module", null)
                        .WithMany()
                        .HasForeignKey("ModulesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CloudDomain.Domain.Page", null)
                        .WithMany()
                        .HasForeignKey("PagesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ReleaseNumberShop", b =>
                {
                    b.HasOne("CloudDomain.Domain.ReleaseNumber", null)
                        .WithMany()
                        .HasForeignKey("ReleaseNumbersID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CloudDomain.Domain.Shop", null)
                        .WithMany()
                        .HasForeignKey("ShopsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ReleaseNumberShopGroup", b =>
                {
                    b.HasOne("CloudDomain.Domain.ReleaseNumber", null)
                        .WithMany()
                        .HasForeignKey("ReleaseNumbersID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CloudDomain.Domain.ShopGroup", null)
                        .WithMany()
                        .HasForeignKey("ShopGroupsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ReportShop", b =>
                {
                    b.HasOne("CloudDomain.Domain.Report", null)
                        .WithMany()
                        .HasForeignKey("ReportsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CloudDomain.Domain.Shop", null)
                        .WithMany()
                        .HasForeignKey("ShopsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.HasOne("CloudDomain.Domain.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CloudDomain.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UsersID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CloudDomain.Domain.Application", b =>
                {
                    b.Navigation("ConnectedApps");

                    b.Navigation("InstallLogs");

                    b.Navigation("ReleaseDetails");

                    b.Navigation("StationApps");
                });

            modelBuilder.Entity("CloudDomain.Domain.EmailSetting", b =>
                {
                    b.Navigation("ShopSettings");
                });

            modelBuilder.Entity("CloudDomain.Domain.Page", b =>
                {
                    b.Navigation("ReleaseDetails");
                });

            modelBuilder.Entity("CloudDomain.Domain.ReleaseNumber", b =>
                {
                    b.Navigation("ReleaseDetails");
                });

            modelBuilder.Entity("CloudDomain.Domain.Report", b =>
                {
                    b.Navigation("ShopSettings");
                });

            modelBuilder.Entity("CloudDomain.Domain.Shop", b =>
                {
                    b.Navigation("EmailLogs");

                    b.Navigation("Stations");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("CloudDomain.Domain.ShopGroup", b =>
                {
                    b.Navigation("Shops");
                });

            modelBuilder.Entity("CloudDomain.Domain.Station", b =>
                {
                    b.Navigation("ConnectedApps");

                    b.Navigation("InstallLogs");

                    b.Navigation("StationApps");
                });
#pragma warning restore 612, 618
        }
    }
}
